# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Standup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Standup
  pod 'AWSAppSync', ' ~> 2.8.0'

  target 'StandupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StandupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
